
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 17.7.0 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /Library/Developer/CommandLineTools/usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is AppleClang, found in:
        /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R"
      binary: "/Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R
        
        Run Build Command(s):/Volumes/Workspace/C++/CLion.app/Contents/bin/ninja/mac/ninja -v cmTC_b0889 && [1/2] /Library/Developer/CommandLineTools/usr/bin/cc   -fcolor-diagnostics   -v -Wl,-v -MD -MT CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -c /Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeCCompilerABI.c
        Apple LLVM version 10.0.0 (clang-1000.10.44.4)
        Target: x86_64-apple-darwin17.7.0
        Thread model: posix
        InstalledDir: /Library/Developer/CommandLineTools/usr/bin
        clang: warning: -Wl,-v: 'linker' input unused [-Wunused-command-line-argument]
         "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -coverage-notes-file /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R/CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.gcno -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0 -dependency-file CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o.d -skip-unused-modulemap-deps -sys-header-deps -MT CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -fdebug-compilation-dir /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.13.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -x c /Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeCCompilerABI.c
        clang -cc1 version 10.0.0 (clang-1000.10.44.4) default target x86_64-apple-darwin17.7.0
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/local/include
         /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include
         /Library/Developer/CommandLineTools/usr/include
         /usr/include
         /System/Library/Frameworks (framework directory)
         /Library/Frameworks (framework directory)
        End of search list.
        [2/2] : && /Library/Developer/CommandLineTools/usr/bin/cc  -Wl,-search_paths_first -Wl,-headerpad_max_install_names -v -Wl,-v CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -o cmTC_b0889   && :
        Apple LLVM version 10.0.0 (clang-1000.10.44.4)
        Target: x86_64-apple-darwin17.7.0
        Thread model: posix
        InstalledDir: /Library/Developer/CommandLineTools/usr/bin
         "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.13.0 -o cmTC_b0889 -search_paths_first -headerpad_max_install_names -v CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a
        @(#)PROGRAM:ld  PROJECT:ld64-409.12
        BUILD 17:47:51 Sep 25 2018
        configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em
        Library search paths:
        	/usr/lib
        	/usr/local/lib
        Framework search paths:
        	/Library/Frameworks/
        	/System/Library/Frameworks/
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/local/include]
          add: [/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include]
          add: [/Library/Developer/CommandLineTools/usr/include]
          add: [/usr/include]
        end of search list found
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include] ==> [/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include]
        collapse include dir [/Library/Developer/CommandLineTools/usr/include] ==> [/Library/Developer/CommandLineTools/usr/include]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/usr/local/include;/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include;/Library/Developer/CommandLineTools/usr/include;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:152 (message)"
      - "/Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R]
        ignore line: []
        ignore line: [Run Build Command(s):/Volumes/Workspace/C++/CLion.app/Contents/bin/ninja/mac/ninja -v cmTC_b0889 && [1/2] /Library/Developer/CommandLineTools/usr/bin/cc   -fcolor-diagnostics   -v -Wl -v -MD -MT CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -c /Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeCCompilerABI.c]
        ignore line: [Apple LLVM version 10.0.0 (clang-1000.10.44.4)]
        ignore line: [Target: x86_64-apple-darwin17.7.0]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /Library/Developer/CommandLineTools/usr/bin]
        ignore line: [clang: warning: -Wl -v: 'linker' input unused [-Wunused-command-line-argument]]
        ignore line: [ "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.13.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-cpu penryn -dwarf-column-info -debugger-tuning=lldb -target-linker-version 409.12 -v -coverage-notes-file /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R/CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.gcno -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0 -dependency-file CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o.d -skip-unused-modulemap-deps -sys-header-deps -MT CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -fdebug-compilation-dir /Volumes/Workspace/CSpace/algorithm/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-1y7m0R -ferror-limit 19 -fmessage-length 0 -stack-protector 1 -fblocks -fencode-extended-block-signature -fobjc-runtime=macosx-10.13.0 -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -x c /Volumes/Workspace/C++/CLion.app/Contents/bin/cmake/mac/share/cmake-3.26/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 10.0.0 (clang-1000.10.44.4) default target x86_64-apple-darwin17.7.0]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/local/include]
        ignore line: [ /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/include]
        ignore line: [ /Library/Developer/CommandLineTools/usr/include]
        ignore line: [ /usr/include]
        ignore line: [ /System/Library/Frameworks (framework directory)]
        ignore line: [ /Library/Frameworks (framework directory)]
        ignore line: [End of search list.]
        ignore line: [[2/2] : && /Library/Developer/CommandLineTools/usr/bin/cc  -Wl -search_paths_first -Wl -headerpad_max_install_names -v -Wl -v CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -o cmTC_b0889   && :]
        ignore line: [Apple LLVM version 10.0.0 (clang-1000.10.44.4)]
        ignore line: [Target: x86_64-apple-darwin17.7.0]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /Library/Developer/CommandLineTools/usr/bin]
        link line: [ "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -macosx_version_min 10.13.0 -o cmTC_b0889 -search_paths_first -headerpad_max_install_names -v CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a]
          arg [/Library/Developer/CommandLineTools/usr/bin/ld] ==> ignore
          arg [-demangle] ==> ignore
          arg [-lto_library] ==> ignore, skip following value
          arg [/Library/Developer/CommandLineTools/usr/lib/libLTO.dylib] ==> skip value of -lto_library
          arg [-dynamic] ==> ignore
          arg [-arch] ==> ignore
          arg [x86_64] ==> ignore
          arg [-macosx_version_min] ==> ignore
          arg [10.13.0] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_b0889] ==> ignore
          arg [-search_paths_first] ==> ignore
          arg [-headerpad_max_install_names] ==> ignore
          arg [-v] ==> ignore
          arg [CMakeFiles/cmTC_b0889.dir/CMakeCCompilerABI.c.o] ==> ignore
          arg [-lSystem] ==> lib [System]
          arg [/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a] ==> lib [/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a]
        Library search paths: [;/usr/lib;/usr/local/lib]
        Framework search paths: [;/Library/Frameworks/;/System/Library/Frameworks/]
        remove lib [System]
        remove lib [/Library/Developer/CommandLineTools/usr/lib/clang/10.0.0/lib/darwin/libclang_rt.osx.a]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        collapse library dir [/usr/local/lib] ==> [/usr/local/lib]
        collapse framework dir [/Library/Frameworks/] ==> [/Library/Frameworks]
        collapse framework dir [/System/Library/Frameworks/] ==> [/System/Library/Frameworks]
        implicit libs: []
        implicit objs: []
        implicit dirs: [/usr/lib;/usr/local/lib]
        implicit fwks: [/Library/Frameworks;/System/Library/Frameworks]
      
      
...
